### ISSUE TITLE
Shadow-root closed?

### ISSUE THREAD

**Issue by jen-power** [jen-power/ecommerce-pattern-library#6]
@thomasjbradley

I tried to add an error icon/svg to my icons.svg Spritesheet but it opened in ImageOptim and I lost everything.

So I re-made the Spritesheet in Spritebot and added the error.svg. I can see all the other icons in my pattern library (including the error icon) but when I go to the site in my browser I see all the icons _except_ for the error icon (which is supposed to show up when a form field isn't filled out correctly. When I inspect the error.svg that isn't showing up I see `#shadow-root (closed)`
What does that mean?

<img width="1125" alt="Screen Shot 2020-03-20 at 3 59 47 PM" src="https://user-images.githubusercontent.com/43247074/77202017-ec122300-6ac3-11ea-97c1-8f5190d0f82f.png">

I also don't remember if before my favicons were set up before ImageOptim erased everything. Does the favicon go into the default.html layout? And do I put the favicon svg's into the Spritesheet?

Thanks

**Comment by thomasjbradley** [comment]
The `#shadow-root` is a secondary, sub-rendering of a web component—rendered separately from the main instance you’re looking at. In the case of the icons, the icon symbol (and all its children elements) are rendered “behind the scenes” then it is just displayed in this location.

But the reason your icon isn’t working is because there’s a `/` missing at the start of the `href`: `xlink:href="/images…"`

**Comment by jen-power** [comment]
Bah, of course! Thanks!
